/* eslint-disable @next/next/no-img-element */
import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { useState, type ChangeEvent, type FormEvent } from "react";
import { Button } from "~/components/Button";
import { FormGroup } from "~/components/FormGroup";
import { Input } from "~/components/Input";
import { api } from "~/utils/api";


const GeneratePage: NextPage = () => {

  const [form, setForm] = useState({
    prompt: "",
  });

  const [imageUrl, setImageUrl] = useState("");

  const generationIcon = api.generate.generateIcon.useMutation({
    onSuccess: (data) => {

      if (!data.imageUrl) return;

      console.log("success", data.imageUrl)

      setImageUrl(data.imageUrl)

    },
  });

  function handleSubmit(e: FormEvent) {
    e.preventDefault();
    // submit form data to the backend
    generationIcon.mutate({
      prompt: form.prompt,
    })
  }

  function updateForm(key: string) {
    return function (e: ChangeEvent<HTMLInputElement>) {
      setForm((prev) => ({
        ...prev,
        [key]: e.target.value
      }));
    }
  }

  const session = useSession();

  const isLoggedIn = !!session.data

  return (<>
    <Head>
      <title>Create</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="flex flex-col min-h-screen justify-center items-center">
      {!isLoggedIn && <Button onClick={() => { signIn().catch(console.error) }} >Login</Button>}
      {isLoggedIn && <Button onClick={() => { signOut().catch(console.error) }} >Logout</Button>}
      <form onSubmit={handleSubmit} className="flex flex-col gap-4">
        <FormGroup>
          <label className="text-gray-100 font-bold text-lg">Prompt</label>
          <Input value={form.prompt} onChange={updateForm("prompt")} type="text" />
        </FormGroup>

        <button className="rounded bg-blue-400 px-4 py-2 hover:bg-blue-500 text-white">Submit</button>
      </form>

      {imageUrl.length > 0 && <Image width="900" height="900" src={`data:image/png;base64,${imageUrl}`} alt="generated image icon" />}
    </main>
  </>);
};

export default GeneratePage;
